version: '3.4'

x-custom:
  service: &service
    image: texlive-2019:latest
    build: ./data/docker-texlive/
    volumes:
      - .:/opt/workdir
    working_dir: /opt/workdir
    user: 1000:1000
  service_env: &service_env
    HOME: /opt/workdir

services:
  texlive:
    <<: *service
    environment:
      <<: *service_env
  lualatex:
    <<: *service
    command: lualatex document.tex
    environment:
      <<: *service_env
  lualatexx:
    <<: *service
    command: lualatex fi-lualatex.tex
    environment:
      <<: *service_env
  pdflatexx:
    <<: *service
    command: pdflatex fi-pdflatex.tex
    environment:
      <<: *service_env
